import type { Activity, BoardMember, BmsaContent, Committee, Division, MerchItem } from './types';

export const siteCopy = {
  en: {
    brand: 'BMSA Benisuef',
    shortBrand: 'BMSA',
    tagline: 'IFMSA-Egypt Local Committee',
    email: 'bmsa.benisuef@gmail.com',
    location: 'Faculty of Medicine, Beni Suef University, Egypt',
    facebook: 'https://www.facebook.com/BMSA.Egypt',
    heroTitle: 'Empowering medical students in Beni Suef',
    heroLead:
      'A student-led medical association creating exchange, education, research, public health, and advocacy opportunities for future doctors.',
    joinCta: 'Join BMSA',
    committeesCta: 'Explore committees',
    nav: {
      home: 'Home',
      about: 'About',
      committees: 'Committees',
      divisions: 'Divisions',
      activities: 'Activities',
      merch: 'Merch',
      join: 'Join',
    },
    stats: [
      ['500+', 'Active Members', 'Building tomorrow\'s physicians'],
      ['40+', 'Campaigns Launched', 'Public health & community impact'],
      ['6', 'Standing Committees', 'Education, exchange, research & more'],
      ['10+', 'Years of Impact', 'IFMSA-Egypt local committee'],
    ],
  },
  ar: {
    brand: 'بمسا بني سويف',
    shortBrand: 'BMSA',
    tagline: 'اللجنة المحلية لـ IFMSA-Egypt',
    email: 'bmsa.benisuef@gmail.com',
    location: 'كلية الطب، جامعة بني سويف، مصر',
    facebook: 'https://www.facebook.com/BMSA.Egypt',
    heroTitle: 'نمكّن طلاب الطب في بني سويف',
    heroLead:
      'جمعية طلابية طبية تفتح فرص التبادل، التعليم الطبي، البحث العلمي، الصحة العامة، والمناصرة لأطباء المستقبل.',
    joinCta: 'انضم إلى بمسا',
    committeesCta: 'استكشف اللجان',
    nav: {
      home: 'الرئيسية',
      about: 'عن بمسا',
      committees: 'اللجان',
      divisions: 'الأقسام',
      activities: 'الأنشطة',
      merch: 'المتجر',
      join: 'انضم',
    },
    stats: [
      ['500+', 'عضو نشط', 'نبني أطباء الغد'],
      ['40+', 'حملة أُطلقت', 'صحة عامة وأثر مجتمعي'],
      ['6', 'لجنة دائمة', 'تعليم، تبادل، بحث علمي والمزيد'],
      ['10+', 'عام من التأثير', 'لجنة محلية في IFMSA-Egypt'],
    ],
  },
};

export const committees: Committee[] = [
  {
    slug: 'scome',
    name: 'SCOME',
    fullName: {
      en: 'Standing Committee on Medical Education',
      ar: 'اللجنة الدائمة للتعليم الطبي',
    },
    description: {
      en: 'Improves medical education through peer teaching, skills workshops, curriculum advocacy, and student representation.',
      ar: 'تطوّر التعليم الطبي عبر التعليم بين الزملاء، ورش المهارات، مناصرة تطوير المناهج، وتمثيل الطلاب.',
    },
    color: '#2f9e44',
    logo: '/images/logos/scome.png',
    programs: [
      { en: 'Clinical Skills Workshops', ar: 'ورش المهارات الإكلينيكية' },
      { en: 'Peer Teaching Sessions', ar: 'جلسات تعليم بين الزملاء' },
      { en: 'OSCE Preparation', ar: 'التحضير لاختبارات OSCE' },
      { en: 'Medical E-Learning', ar: 'التعليم الطبي الرقمي' },
    ],
  },
  {
    slug: 'scope',
    name: 'SCOPE',
    fullName: {
      en: 'Standing Committee on Professional Exchanges',
      ar: 'اللجنة الدائمة للتبادل المهني',
    },
    description: {
      en: 'Runs clinical exchange opportunities that help students experience healthcare systems around the world.',
      ar: 'تنظم فرص التبادل الإكلينيكي ليستكشف الطلاب أنظمة الرعاية الصحية حول العالم.',
    },
    color: '#1971c2',
    logo: '/images/logos/scope.png',
    programs: [
      { en: 'Outgoing Exchanges', ar: 'التبادل الخارجي' },
      { en: 'Incoming Exchanges', ar: 'استقبال طلاب التبادل' },
      { en: 'Clinical Orientation', ar: 'التهيئة الإكلينيكية' },
      { en: 'Language Preparation', ar: 'التحضير اللغوي' },
    ],
  },
  {
    slug: 'scoph',
    name: 'SCOPH',
    fullName: {
      en: 'Standing Committee on Public Health',
      ar: 'اللجنة الدائمة للصحة العامة',
    },
    description: {
      en: 'Builds community health campaigns, screenings, and awareness programs across Beni Suef.',
      ar: 'تنفذ حملات صحة عامة، فحوصات، وبرامج توعية مجتمعية داخل بني سويف.',
    },
    color: '#d6336c',
    logo: '/images/logos/scoph.png',
    programs: [
      { en: 'Free Screening Clinics', ar: 'قوافل فحص مجانية' },
      { en: 'School Health Programs', ar: 'برامج صحة مدرسية' },
      { en: 'Vaccination Drives', ar: 'حملات تطعيم' },
      { en: 'Health Awareness Days', ar: 'أيام توعية صحية' },
    ],
  },
  {
    slug: 'scora',
    name: 'SCORA',
    fullName: {
      en: 'Standing Committee on Sexual and Reproductive Health and Rights including HIV and AIDS',
      ar: 'اللجنة الدائمة للصحة والحقوق الجنسية والإنجابية بما يشمل HIV/AIDS',
    },
    description: {
      en: 'Promotes reproductive health, HIV awareness, gender equity, and youth-friendly health education.',
      ar: 'تعزز الصحة الإنجابية، التوعية بفيروس HIV، العدالة الجندرية، والتثقيف الصحي المناسب للشباب.',
    },
    color: '#e8590c',
    logo: '/images/logos/scora.png',
    programs: [
      { en: 'World AIDS Day Events', ar: 'فعاليات اليوم العالمي للإيدز' },
      { en: 'Gender and Health Workshops', ar: 'ورش النوع الاجتماعي والصحة' },
      { en: 'Maternal Health Programs', ar: 'برامج صحة الأم' },
      { en: 'Youth Health Education', ar: 'تثقيف صحي للشباب' },
    ],
  },
  {
    slug: 'score',
    name: 'SCORE',
    fullName: {
      en: 'Standing Committee on Research Exchanges',
      ar: 'اللجنة الدائمة للتبادل البحثي',
    },
    description: {
      en: 'Connects students with research projects, scientific writing, statistics training, and research exchange opportunities.',
      ar: 'تربط الطلاب بالمشاريع البحثية، الكتابة العلمية، تدريب الإحصاء، وفرص التبادل البحثي.',
    },
    color: '#862e9c',
    logo: '/images/logos/score.png',
    programs: [
      { en: 'Research Exchanges Abroad', ar: 'تبادل بحثي بالخارج' },
      { en: 'Journal Club', ar: 'نادي قراءة الأبحاث' },
      { en: 'Scientific Writing', ar: 'الكتابة العلمية' },
      { en: 'Statistics Training', ar: 'تدريب الإحصاء' },
    ],
  },
  {
    slug: 'scorp',
    name: 'SCORP',
    fullName: {
      en: 'Standing Committee on Human Rights and Peace',
      ar: 'اللجنة الدائمة لحقوق الإنسان والسلام',
    },
    description: {
      en: 'Advocates for human rights, refugee health, medical ethics, inclusion, peace, and social justice.',
      ar: 'تناصر حقوق الإنسان، صحة اللاجئين، أخلاقيات الطب، الدمج، السلام، والعدالة الاجتماعية.',
    },
    color: '#0c8599',
    logo: '/images/logos/scorp.png',
    programs: [
      { en: 'Human Rights in Medicine', ar: 'حقوق الإنسان في الطب' },
      { en: 'Refugee Health Programs', ar: 'برامج صحة اللاجئين' },
      { en: 'Medical Ethics Workshops', ar: 'ورش أخلاقيات الطب' },
      { en: 'SDG Campaigns', ar: 'حملات أهداف التنمية المستدامة' },
    ],
  },
];

export const divisions: Division[] = [
  {
    slug: 'cbsd',
    name: 'CBSD',
    fullName: { en: 'Capacity Building Support Division', ar: 'قسم دعم بناء القدرات' },
    description: {
      en: 'Trains members and develops internal capacity so every committee can lead better projects.',
      ar: 'يدرّب الأعضاء ويطوّر القدرات الداخلية لتقود كل لجنة مشاريع أقوى.',
    },
    color: '#1e1e17',
    logo: '/images/logos/divisions/cbsd.png',
  },
  {
    slug: 'psd',
    name: 'PSD',
    fullName: { en: 'Project Support Division', ar: 'قسم دعم المشاريع' },
    description: {
      en: 'Supports focus areas, project design, monitoring, and activity quality across BMSA.',
      ar: 'يدعم مجالات التركيز، تصميم المشاريع، المتابعة، وجودة الأنشطة داخل بمسا.',
    },
    color: '#107a72',
    logo: '/images/logos/divisions/psd.png',
  },
  {
    slug: 'pnsd',
    name: 'PNSD',
    fullName: { en: 'Publications and New Technologies Support Division', ar: 'قسم المنشورات والتقنيات الحديثة' },
    description: {
      en: 'Owns digital presence, publications, visual identity, media production, and technology workflows.',
      ar: 'يدير الحضور الرقمي، المنشورات، الهوية البصرية، الإنتاج الإعلامي، وسير العمل التقني.',
    },
    color: '#9f1547',
    logo: '/images/logos/divisions/pnsd.png',
  },
  {
    slug: 'fsd',
    name: 'FSD',
    fullName: { en: 'Fundraising Support Division', ar: 'قسم دعم جمع التبرعات' },
    description: {
      en: 'Builds partnerships and fundraising plans that keep projects sustainable.',
      ar: 'يبني شراكات وخطط جمع تبرعات تجعل المشاريع أكثر استدامة.',
    },
    color: '#8b4514',
    logo: '/images/logos/divisions/fsd.png',
  },
  {
    slug: 'rsd',
    name: 'RSD',
    fullName: { en: 'Research Support Division', ar: 'قسم دعم البحث العلمي' },
    description: {
      en: 'Encourages scientific thinking, research mentorship, evidence-based medicine, and open science.',
      ar: 'يشجع التفكير العلمي، الإرشاد البحثي، الطب المبني على الدليل، والعلم المفتوح.',
    },
    color: '#f7b826',
    logo: '/images/logos/divisions/rsd.png',
  },
];

export const activities: Activity[] = [
  {
    slug: 'world-aids-day',
    committee: 'scora',
    title: { en: 'World AIDS Day Campaign', ar: 'حملة اليوم العالمي للإيدز' },
    excerpt: {
      en: 'Community awareness and stigma reduction campaign for HIV prevention and testing.',
      ar: 'حملة توعية مجتمعية لتقليل الوصمة والتعريف بطرق الوقاية والفحص.',
    },
    description: {
      en: 'SCORA organized a public awareness day covering HIV prevention, testing, and community support with youth-friendly education.',
      ar: 'نظمت SCORA يوم توعية عام عن الوقاية من HIV، الفحص، والدعم المجتمعي بمحتوى مناسب للشباب.',
    },
    tag: { en: 'SCORA - Public Campaign', ar: 'SCORA - حملة عامة' },
    imageUrl: null,
    icon: 'ribbon',
    sortOrder: 1,
  },
  {
    slug: 'clinical-exchange-germany',
    committee: 'scope',
    title: { en: 'Clinical Exchange - Germany', ar: 'تبادل إكلينيكي - ألمانيا' },
    excerpt: {
      en: 'Students joined a four-week clerkship and explored a new healthcare system.',
      ar: 'شارك الطلاب في تدريب إكلينيكي لأربعة أسابيع واختبروا نظاماً صحياً جديداً.',
    },
    description: {
      en: 'SCOPE supported outgoing students before, during, and after their clinical clerkship abroad.',
      ar: 'دعمت SCOPE الطلاب المسافرين قبل وأثناء وبعد فترة التدريب الإكلينيكي بالخارج.',
    },
    tag: { en: 'SCOPE - Exchange', ar: 'SCOPE - تبادل' },
    imageUrl: null,
    icon: 'plane',
    sortOrder: 2,
  },
  {
    slug: 'cardiovascular-health-week',
    committee: 'scoph',
    title: { en: 'Cardiovascular Health Week', ar: 'أسبوع صحة القلب والأوعية الدموية' },
    excerpt: {
      en: 'Screening and awareness for blood pressure, lifestyle risk, and prevention.',
      ar: 'فحوصات وتوعية بضغط الدم، عوامل الخطورة، وطرق الوقاية.',
    },
    description: {
      en: 'SCOPH brought health education and basic screening closer to students and community members.',
      ar: 'قرّبت SCOPH التثقيف الصحي والفحوصات الأساسية من الطلاب وأفراد المجتمع.',
    },
    tag: { en: 'SCOPH - Health Campaign', ar: 'SCOPH - حملة صحية' },
    imageUrl: null,
    icon: 'heart-pulse',
    sortOrder: 3,
  },
  {
    slug: 'clinical-skills-bootcamp',
    committee: 'scome',
    title: { en: 'Clinical Skills Bootcamp', ar: 'معسكر المهارات الإكلينيكية' },
    excerpt: {
      en: 'Hands-on training for examination skills, communication, and OSCE readiness.',
      ar: 'تدريب عملي على مهارات الفحص، التواصل، والاستعداد لاختبارات OSCE.',
    },
    description: {
      en: 'SCOME built a peer-led training space for students to practice core clinical skills safely.',
      ar: 'أنشأت SCOME مساحة تدريب يقودها الطلاب لممارسة المهارات الإكلينيكية الأساسية بثقة.',
    },
    tag: { en: 'SCOME - Education', ar: 'SCOME - تعليم طبي' },
    imageUrl: null,
    icon: 'stethoscope',
    sortOrder: 4,
  },
  {
    slug: 'scientific-writing-workshop',
    committee: 'score',
    title: { en: 'Scientific Writing Workshop', ar: 'ورشة الكتابة العلمية' },
    excerpt: {
      en: 'A practical workshop on abstracts, papers, citations, and research communication.',
      ar: 'ورشة عملية عن الملخصات، الأوراق العلمية، التوثيق، والتواصل البحثي.',
    },
    description: {
      en: 'SCORE helped students turn research questions into clearer scientific writing.',
      ar: 'ساعدت SCORE الطلاب على تحويل الأسئلة البحثية إلى كتابة علمية أوضح.',
    },
    tag: { en: 'SCORE - Research', ar: 'SCORE - بحث علمي' },
    imageUrl: null,
    icon: 'file-pen',
    sortOrder: 5,
  },
  {
    slug: 'refugee-health-awareness',
    committee: 'scorp',
    title: { en: 'Refugee Health Awareness Day', ar: 'يوم التوعية بصحة اللاجئين' },
    excerpt: {
      en: 'Human rights and health education focused on access, dignity, and inclusion.',
      ar: 'توعية بحقوق الإنسان والصحة مع التركيز على الوصول، الكرامة، والدمج.',
    },
    description: {
      en: 'SCORP linked medical ethics with practical advocacy for vulnerable communities.',
      ar: 'ربطت SCORP أخلاقيات الطب بالمناصرة العملية للفئات الأكثر احتياجاً.',
    },
    tag: { en: 'SCORP - Advocacy', ar: 'SCORP - مناصرة' },
    imageUrl: null,
    icon: 'scale',
    sortOrder: 6,
  },
];

export const merchItems: MerchItem[] = [
  {
    slug: 'hoodie',
    name: { en: 'BMSA Hoodie', ar: 'هودي بمسا' },
    description: {
      en: 'Heavyweight hoodie with embroidered BMSA logo.',
      ar: 'هودي ثقيل مع شعار بمسا مطرّز.',
    },
    price: { en: 'Contact for price', ar: 'تواصل لمعرفة السعر' },
    imageUrl: null,
    icon: 'shirt',
    gradient: 'linear-gradient(135deg,#c0392b,#922b21)',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    hasSizes: true,
    inStock: true,
    sortOrder: 1,
  },
  {
    slug: 'tshirt',
    name: { en: 'BMSA T-shirt', ar: 'تيشيرت بمسا' },
    description: {
      en: 'Cotton T-shirt with BMSA Benisuef front and back print.',
      ar: 'تيشيرت قطن بطباعة بمسا بني سويف أمامية وخلفية.',
    },
    price: { en: 'Contact for price', ar: 'تواصل لمعرفة السعر' },
    imageUrl: null,
    icon: 'shirt',
    gradient: 'linear-gradient(135deg,#1565c0,#42a5f5)',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    hasSizes: true,
    inStock: true,
    sortOrder: 2,
  },
  {
    slug: 'labcoat',
    name: { en: 'Lab Coat', ar: 'روب المختبر' },
    description: {
      en: 'White medical lab coat with embroidered BMSA logo.',
      ar: 'روب طبي أبيض مع شعار بمسا مطرّز.',
    },
    price: { en: 'Contact for price', ar: 'تواصل لمعرفة السعر' },
    imageUrl: null,
    icon: 'stethoscope',
    gradient: 'linear-gradient(135deg,#607d8b,#90a4ae)',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    hasSizes: true,
    inStock: true,
    sortOrder: 3,
  },
  {
    slug: 'lanyard',
    name: { en: 'BMSA Lanyard', ar: 'حمالة البطاقة' },
    description: {
      en: 'Durable branded lanyard with metal clip and badge holder.',
      ar: 'حمالة بطاقة متينة بشعار بمسا ومشبك معدني.',
    },
    price: { en: 'Contact for price', ar: 'تواصل لمعرفة السعر' },
    imageUrl: null,
    icon: 'badge',
    gradient: 'linear-gradient(135deg,#f5a623,#d4901f)',
    sizes: [],
    hasSizes: false,
    inStock: true,
    sortOrder: 4,
  },
  {
    slug: 'notebook',
    name: { en: 'BMSA Notebook', ar: 'دفتر بمسا' },
    description: {
      en: 'A5 hard-cover notebook with BMSA logo.',
      ar: 'دفتر A5 بغلاف صلب وشعار بمسا.',
    },
    price: { en: 'Contact for price', ar: 'تواصل لمعرفة السعر' },
    imageUrl: null,
    icon: 'book',
    gradient: 'linear-gradient(135deg,#388e3c,#66bb6a)',
    sizes: [],
    hasSizes: false,
    inStock: true,
    sortOrder: 5,
  },
  {
    slug: 'stickers',
    name: { en: 'Sticker Pack', ar: 'مجموعة الستيكرات' },
    description: {
      en: 'Vinyl sticker pack for BMSA and committees.',
      ar: 'مجموعة ستيكرات فينيل لبمسا واللجان.',
    },
    price: { en: 'Contact for price', ar: 'تواصل لمعرفة السعر' },
    imageUrl: null,
    icon: 'sparkles',
    gradient: 'linear-gradient(135deg,#9f1547,#f06292)',
    sizes: [],
    hasSizes: false,
    inStock: true,
    sortOrder: 6,
  },
  {
    slug: 'mug',
    name: { en: 'BMSA Mug', ar: 'كوب بمسا' },
    description: {
      en: 'Ceramic 350ml mug with BMSA logo.',
      ar: 'كوب سيراميك 350 مل بشعار بمسا.',
    },
    price: { en: 'Contact for price', ar: 'تواصل لمعرفة السعر' },
    imageUrl: null,
    icon: 'mug',
    gradient: 'linear-gradient(135deg,#5d4037,#a1887f)',
    sizes: [],
    hasSizes: false,
    inStock: true,
    sortOrder: 7,
  },
  {
    slug: 'tote',
    name: { en: 'Tote Bag', ar: 'شنطة توت باج' },
    description: {
      en: 'Daily canvas tote bag with BMSA print.',
      ar: 'حقيبة قماشية يومية بطباعة بمسا.',
    },
    price: { en: 'Contact for price', ar: 'تواصل لمعرفة السعر' },
    imageUrl: null,
    icon: 'bag',
    gradient: 'linear-gradient(135deg,#107a72,#26c6da)',
    sizes: [],
    hasSizes: false,
    inStock: true,
    sortOrder: 8,
  },
];

export const boardMembers: BoardMember[] = [
  {
    tier: 'eb',
    positionTitle: { en: 'President', ar: 'الرئيس' },
    role: { en: 'BMSA Benisuef', ar: 'بمسا بني سويف' },
    memberName: { en: 'TBD', ar: 'يُعلن لاحقاً' },
    imageUrl: null,
    icon: 'user',
    gradient: 'linear-gradient(135deg,#c0392b,#e15a4a)',
    sortOrder: 1,
  },
  {
    tier: 'eb',
    positionTitle: { en: 'Vice President for Internal Affairs', ar: 'نائب الرئيس للشؤون الداخلية' },
    role: { en: 'Executive Board', ar: 'المجلس التنفيذي' },
    memberName: { en: 'TBD', ar: 'يُعلن لاحقاً' },
    imageUrl: null,
    icon: 'user',
    gradient: 'linear-gradient(135deg,#922b21,#c0392b)',
    sortOrder: 2,
  },
  {
    tier: 'eb',
    positionTitle: { en: 'Vice President for External Affairs', ar: 'نائب الرئيس للشؤون الخارجية' },
    role: { en: 'Executive Board', ar: 'المجلس التنفيذي' },
    memberName: { en: 'TBD', ar: 'يُعلن لاحقاً' },
    imageUrl: null,
    icon: 'user',
    gradient: 'linear-gradient(135deg,#b03a2e,#f5a623)',
    sortOrder: 3,
  },
  {
    tier: 'to',
    positionTitle: { en: 'SCOME Officer', ar: 'مسؤول SCOME' },
    role: { en: 'Technical Officer', ar: 'مسؤول تقني' },
    memberName: { en: 'TBD', ar: 'يُعلن لاحقاً' },
    imageUrl: null,
    icon: 'user',
    gradient: 'linear-gradient(135deg,#2f9e44,#69db7c)',
    sortOrder: 4,
  },
  {
    tier: 'to',
    positionTitle: { en: 'SCOPE and SCORE Officer', ar: 'مسؤول SCOPE و SCORE' },
    role: { en: 'Technical Officer', ar: 'مسؤول تقني' },
    memberName: { en: 'TBD', ar: 'يُعلن لاحقاً' },
    imageUrl: null,
    icon: 'user',
    gradient: 'linear-gradient(135deg,#1971c2,#862e9c)',
    sortOrder: 5,
  },
  {
    tier: 'to',
    positionTitle: { en: 'SCOPH Officer', ar: 'مسؤول SCOPH' },
    role: { en: 'Technical Officer', ar: 'مسؤول تقني' },
    memberName: { en: 'TBD', ar: 'يُعلن لاحقاً' },
    imageUrl: null,
    icon: 'user',
    gradient: 'linear-gradient(135deg,#d6336c,#f783ac)',
    sortOrder: 6,
  },
  {
    tier: 'to',
    positionTitle: { en: 'SCORA Officer', ar: 'مسؤول SCORA' },
    role: { en: 'Technical Officer', ar: 'مسؤول تقني' },
    memberName: { en: 'TBD', ar: 'يُعلن لاحقاً' },
    imageUrl: null,
    icon: 'user',
    gradient: 'linear-gradient(135deg,#e8590c,#ff922b)',
    sortOrder: 7,
  },
  {
    tier: 'to',
    positionTitle: { en: 'SCORP Officer', ar: 'مسؤول SCORP' },
    role: { en: 'Technical Officer', ar: 'مسؤول تقني' },
    memberName: { en: 'TBD', ar: 'يُعلن لاحقاً' },
    imageUrl: null,
    icon: 'user',
    gradient: 'linear-gradient(135deg,#0c8599,#66d9e8)',
    sortOrder: 8,
  },
];

export const fallbackContent: BmsaContent = {
  committees,
  divisions,
  activities,
  merchItems,
  boardMembers,
  images: {},
};
